#include <RcppDist.h>
#include <iostream>
#include <vector>
#include <map>
#include <stack>
#include <string>

// [[Rcpp::depends(RcppArmadillo, RcppDist)]]

// #include <omp.h>
// // [[Rcpp::plugins(openmp)]]


//----------------------------------------------------------------
// HELPER FUNCTIONS

// generated by ChatGPT
// This hashing algorithm is good for hashing vectors
static inline uint64_t hash_perm(const int* v, int r) {
  // FNV-1a variant with mix. collisions are astronomically unlikely for typical r
  uint64_t h = 1469598103934665603ull;
  for (int i = 0; i < r; ++i) {
    uint64_t x = (uint64_t)(uint32_t)v[i] + 0x9e3779b97f4a7c15ull;
    h ^= x;
    h *= 1099511628211ull;
    h ^= (h >> 33);
    h *= 0xff51afd7ed558ccdull;
    h ^= (h >> 33);
  }
  return h;
}


// [[Rcpp::export]]
Rcpp::List flatten_blocks(Rcpp::List& blocks) {
  
  Rcpp::List return_seq;
  
  for(int i = 0; i < blocks.size(); i++) {
    Rcpp::List current_block = blocks[i];
    for(int j = 0; j < current_block.size(); j++) {
      return_seq.push_back(current_block[j]);
    }
  }
  
  return return_seq;

}


/*
 * Inputs: a and b as lists
 * Outputs: True if same else False
 */
// [[Rcpp::export]]
inline bool same_pair(const Rcpp::IntegerVector& a,
                      const Rcpp::IntegerVector& b) {
  // ensure both are length 2
  if (a.size() != 2 || b.size() != 2 || a.size() > 2 || b.size() > 2) return false;
  
  // check element-wise equality (order matters)
  return a[0] == b[0] && a[1] == b[1];
}


/*
 * capped permutation count formula.
 * Multiplies until the cap is reached to avoid overflow
 * returns min(n_P_{min(n,r)}, cap)
 */
//[[Rcpp::export]]
long long nPr_capped_max(int n, int r, long long cap) {
  int r_temp = r;
  if (r < 0) return 0;
  if (r > n) r_temp = n;
  long long res = 1;
  for (int k = 0; k < r_temp; k++) {
    int term = n - k;
    if (res > cap / term) return cap + 1;
    res *= term;
  }
  return res;
}


//[[Rcpp::export]]
Rcpp::List sample_from_list(Rcpp::List x, int k) {
  int n = x.size();
  if (k > n) k = n;
  // sample indices without replacement
  Rcpp::IntegerVector idx = Rcpp::sample(n, k, false);
  Rcpp::List out(k);
  for (int i = 0; i < k; i++)
    out[i] = x[idx[i] - 1];
  return out;
}


//[[Rcpp::export]]
std::string list_to_string(Rcpp::List x) {
  std::ostringstream oss;
  int n = x.size();
  for (int i = 0; i < n; i++) {
    double val = Rcpp::as<double>(x[i]);
    oss << static_cast<int>(val);
    if (i != n - 1) oss << ",";
  }
  return oss.str();
}


/*
 * uses the swapping algorithm to get all partial permutations of length r
 * from list indices
 * Inputs: indices list, int r
 */
// [[Rcpp::export]]
Rcpp::List all_r_perms_list(Rcpp::IntegerVector indices, int r) {
  int n = indices.size();
  int r_temp = r;
  if (r < 0) return Rcpp::List();
  if (r > n) r_temp = n;
  
  // put all indices in a vector
  std::vector<int> A(n);
  for (int i = 0; i < n; i++) {
    A[i] = indices[i]; 
  }
  
  // create a vector of lists called out
  std::vector<Rcpp::IntegerVector> out;
  
  // Use a recursive lambda to implement the swapping algorithm for partial
  // permutations.
  std::function<void(int)> dfs = [&](int i) {
    // basecase: if we have already chosen r elements,
    // return after storing the valid permutation in out.
    if (i == r_temp) {
      Rcpp::IntegerVector one(r_temp);
      for (int t = 0; t < r_temp; t++) one[t] = A[t];
      out.push_back(one);
      return;
    }
    // recursive case:
    for (int j = i; j < n; j++) {
      std::swap(A[i], A[j]);
      dfs(i + 1);
      std::swap(A[i], A[j]);   // backtrack
    }
  };
  
  dfs(0);
  
  // Pack vector<List> -> List
  Rcpp::List res(out.size());
  for (size_t i = 0; i < out.size(); i++) res[i] = out[i];
  return res;
}

/**
 * incorporates permutation sampling
 */
// [[Rcpp::export]]
Rcpp::List r_permutations(
    Rcpp::IntegerVector indices,
    int r,
    int num_perms_wanted) 
{
  
  int n = indices.size();
  int r_use = std::min(r, n);
  
  Rcpp::RNGScope scope;
  
  int num_perms_available = nPr_capped_max(indices.size(), r, num_perms_wanted * 3);

  if (num_perms_wanted >= num_perms_available) {
    // asking for as many or more permutations than are available
    // get complete set of permutations
    return all_r_perms_list(indices, r);
    
  } else if (num_perms_wanted <= 0.5 * num_perms_available) {
    // if number of permutations available is more than twice the number of permutations being
    // asked for,
    // sample permutations randomly
    
    // stores the chosen permutations
    Rcpp::List chosen_perms;
    
    // contains a pool of indices to shuffle
    std::vector<int> pool(n);
    for (int i = 0; i < n; ++i) pool[i] = indices[i];
    
    // get a working copy
    std::vector<int> a = pool;
    
    // an unordered set of list hashes
    // faster than turning lists into strings
    std::unordered_set<uint64_t> seen;
    seen.reserve((size_t)num_perms_wanted * 2);
    
    int num_chosen = 0;
    
    while (num_chosen < num_perms_wanted) {
      
      a = pool;  // reset working copy (simple and fast for moderate n)
      
      // this swaps the first min(r, n) elements with elements from random indices.
      // this works because all indices are guaranteed to be different.
      // partial shuffle
      for (int i = 0; i < r_use; i++) {
        int j = i + (int)std::floor(R::runif(0.0, 1.0) * (n - i));
        std::swap(a[i], a[j]);
      }
      
      // hash all of "a"
      // hashing algorithm is dependent on order of "a"
      uint64_t h = hash_perm(a.data(), r_use);
      
      // is h in the unordered set seen?
      if (seen.insert(h).second) {
        Rcpp::IntegerVector out(r_use);
        for (int i = 0; i < r_use; i++) out[i] = a[i];
        chosen_perms.push_back(out);
        num_chosen += 1;
      }
    }
    
    return chosen_perms;
    
  } else if (num_perms_wanted > 0.5 * num_perms_available && num_perms_wanted < num_perms_available) {
    // if number of permutations being asked for is close to the number of permutations available
    // get complete set of permutations
    // sample permutations randomly.
    Rcpp::List perms = all_r_perms_list(indices, r);
    Rcpp::List chosen_perms;
    int num_chosen = 0;
    
    std::unordered_set<int> seen;
    
    while (num_chosen < num_perms_wanted) {
      int idx = (int) std::floor(R::runif(0.0, 1.0) * perms.size());
      if (seen.insert(idx).second) {
        chosen_perms.push_back(perms[idx]);
        num_chosen += 1;
      }
    }
    return chosen_perms;
    
  } else {
    
    return all_r_perms_list(indices, r);
    
  }

}


//----------------------------------------------------------------
/*
 * Estimate observation probabilities
 * Input: sequence as Rcpp list, int k
 * Return: P estimated probability transition matrix
*/
// [[Rcpp::export]]
arma::mat estimate_transition_probabilities(Rcpp::List& sequence, int k) {
  int n = sequence.size();
  // initialize count matrix
  arma::mat counts = arma::zeros<arma::mat>(k, k);
  
  // count transitions
  for (int t = 0; t < n - 1; t++) {
    Rcpp::IntegerVector pair_t = sequence[t];
    Rcpp::IntegerVector pair_tp1 = sequence[t + 1];
    int i = pair_t[0]; // state of element t
    int j = pair_tp1[0]; // state of element t + 1
    counts(i, j) += 1.0; // counts
  }
  
  arma::vec row_sums = arma::sum(counts, 1);  // sum across columns (sum of each row)
  
  arma::mat P = arma::zeros<arma::mat>(k, k);
  for (int i = 0; i < k; i++) {
    if (row_sums[i] > 0) {
      P.row(i) = counts.row(i) / row_sums[i]; // normalize each row
    } else {
      P(i, i) = 1;
    }
  }
  return P; // return final matrix
}


//----------------------------------------------------------------
/*
 * Estimate observation probabilities
 * Input: sequence as Rcpp list, int k, int m
 * Return: B estimated probability observation matrix
 */
// [[Rcpp::export]]
arma::mat estimate_observation_probabilities(Rcpp::List& sequence, int k, int m) {
  int n = sequence.size();
  // initialize count matrix
  arma::mat counts = arma::zeros<arma::mat>(k, m);
  
  // count transitions
  for (int t = 0; t < n; ++t) {
    Rcpp::IntegerVector pair_t = sequence[t];
    int i = pair_t[0];
    int j = pair_t[1];
    counts(i, j) += 1.0;
  }
  
  arma::vec row_sums = arma::sum(counts, 1);  // sum across columns (sum of each row)
  
  arma::mat B = arma::zeros<arma::mat>(k, m);
  for (int i = 0; i < k; i++) {
    if (row_sums[i] > 0) {
      B.row(i) = counts.row(i) / row_sums[i];
    }
  }
  return B;
}


//----------------------------------------------------------------
/*
 * Get ij blocks
 * Not actually all ij blocks, but a divider function.
 * Input: sequence as Rcpp list
 * Return: List of ij blocks
 */
// [[Rcpp::export]]
Rcpp::List ij_blocks(Rcpp::List& sequence) {
  
  int n = sequence.size();
  
  Rcpp::IntegerVector ij_pair = Rcpp::as<Rcpp::IntegerVector>(sequence[n - 1]);
  
  Rcpp::List blocks;
  Rcpp::List current_collection;
  
  for (int i = 0; i < n; i++) {
    
    if (i == 0) {
      
      current_collection.push_back(sequence[i]);
      
    } else {
      
      Rcpp::IntegerVector cur = Rcpp::as<Rcpp::IntegerVector>(sequence[i]);
      if (same_pair(cur, ij_pair)) {
        blocks.push_back(current_collection);
        current_collection = Rcpp::List::create(sequence[i]);
      } else {
        current_collection.push_back(sequence[i]);
      }
      
    }
  }
  
  blocks.push_back(current_collection);
  return blocks;
  
}


//----------------------------------------------------------------
/*
 * Given the list of all blocks, create permuted lists on which the
 * nonconformity function can operate.
 * blocks is a list of lists. Each list in blocks contains mutiple pairs as lists.
 * 
 */
// [[Rcpp::export]]
Rcpp::List create_permutes(Rcpp::List& blocks, int test_len, int max_perms) {
  // contains the list of all permutable ij blocks
  Rcpp::IntegerVector permutable_indices;

  int n = blocks.size();
  bool first_block_included = false;

  Rcpp::List last_block = blocks[n - 1];
  Rcpp::IntegerVector last_pair =
    Rcpp::as<Rcpp::IntegerVector>(last_block[last_block.size() - 1]);

  // gets the permutable indices within fragmented sequence
  for (int i = 0; i < n; i++) {

    Rcpp::List current_block = blocks[i];
    Rcpp::IntegerVector interest_pair =
      Rcpp::as<Rcpp::IntegerVector>(current_block[0]);

    if (same_pair(interest_pair, last_pair)
          && i != n - 1) {
      permutable_indices.push_back(i);
      if (i == 0) {
        first_block_included = true;
      }
    }
  }

  // permutes the indices for the permutable ij blocks
  Rcpp::List permutes = r_permutations(permutable_indices, test_len, max_perms);
  
  Rcpp::List return_lst;
  for (int i = 0; i < permutes.size(); i++) {

    Rcpp::IntegerVector perm = Rcpp::as<Rcpp::IntegerVector>(permutes[i]);
    std::vector<int> perm_vec(perm.size());
    for (int i = 0; i < perm.size(); i++) perm_vec[i] = perm[i];

    Rcpp::List current_block_lst;

    // If the first block is not permutable, include it in the
    // current block list (as safety)
    if (!first_block_included) {
      current_block_lst.push_back(
        Rcpp::as<Rcpp::List>(blocks[0])
      );
    }

    // For each index in the current permutation
    // get the block at that index amd store in
    // current_block_lst
    for (int p = 0; p < perm.size(); p++) {
      int x = perm_vec[p];
      Rcpp::List current_block = Rcpp::as<Rcpp::List>(blocks[x]);
      current_block_lst.push_back(
        current_block
      );
    }

    // push the last block in
    current_block_lst.push_back(
      Rcpp::as<Rcpp::List>(blocks[blocks.size() - 1])
    );

    // flatten the current block list and push the result into return_lst
    return_lst.push_back(
      flatten_blocks(current_block_lst)
    );
  }

  // in the case that nothing is in the return list (no permutations)
  if (return_lst.size() == 0) {
    return_lst.push_back(
      flatten_blocks(blocks)
    );
  }

  return return_lst;
}


//----------------------------------------------------------------
/*
 * gets the sum shown in step 13 of algorithm
 * Assumptions:
 * rows of P and B must sum to 1
 * 
 */
// [[Rcpp::export]]
double filter_subroutine_sum(
  arma::mat& P,
  arma::mat& B,
  int test_len,
  Rcpp::List& sequence)
{
  
  for (Rcpp::IntegerVector x: sequence) {
    if (x.size() != 2) {
      Rcpp::stop("Unacceptable sequence");
    }
  }

  // get sequence size and number of states
  int n = sequence.size();
  int k = P.n_rows;

  // test_len and start_idx checks
  if (test_len <= 0 || n == 0) return 0.0;
  if (test_len > n - 1) {
    Rcpp::stop("test_len (%d) is too large for sequence length (%d).", test_len, n);
  }
  int start_idx = n - test_len - 1;
  if (start_idx < 0) return 0.0;

  // additional checks
  if (k <= 0) {
    Rcpp::stop("P must be non-empty.");
  }
  if ((int)P.n_cols != k) {
    Rcpp::stop("P must be square k x k.");
  }
  if ((int)B.n_rows != k) {
    Rcpp::stop("B must have k rows.");
  }

  Rcpp::IntegerVector first_pair = sequence[start_idx];
  if (first_pair.size() != 2) {
    Rcpp::stop("sequence[%d] is not a 2-element tuple.", start_idx + 1);
  }

  int s0 = first_pair[0];
  if (s0 < 0 || s0 >= k) {
    Rcpp::stop("State index out of bounds at start: %d (k=%d).", s0, k);
  }

  // holds the probabilities across test sequence.
  std::vector<arma::vec> prob_vecs;
  prob_vecs.reserve(test_len + 1);

  // length of vectors correspond to number of possible states
  arma::vec first_vec = arma::zeros<arma::vec>(k);
  // index s0 in vector is 1
  first_vec(s0) = 1.0;
  // push back vector
  prob_vecs.push_back(first_vec);

  // P transpose
  arma::mat Pt = P.t();

  // start at T + 1 and go all the way to T + T1
  for (int i = start_idx + 1; i <= start_idx + test_len; i++) {
    // take current observation
    Rcpp::IntegerVector current_pair = sequence[i];

    int obs_next = current_pair[1];

    const arma::vec& prev = prob_vecs.back();         // p_{i-1}
    arma::vec temp = B.col(obs_next) % (Pt * prev);   // diag(B_{y_{i}}) * P^T * p_{i-1}

    // stabilize & normalize
    double s = arma::accu(temp);
    temp /= s;

    prob_vecs.push_back(std::move(temp));             // this is p_{i+1}
  }

  double return_sum = 0.0;
  for (int i = 0; i < test_len; i++) {
    Rcpp::IntegerVector pair_ip1 = sequence[start_idx + i + 1];
    int st_next = pair_ip1[0];
    return_sum += prob_vecs[i + 1](st_next);
  }
  return return_sum;
}

// [[Rcpp::export]]
Rcpp::List get_cp_set(
  Rcpp::List& sequence,
  Rcpp::IntegerVector& test_observations,
  int pred_len, int num_perms, int k, int m, 
  double alpha,
  bool add_zero,
  std::string mode,
  const arma::mat &allowable_transitions,
  bool coin_flip = true
) {
  
  arma::mat allowed;
  
  if (allowable_transitions.n_elem == 0) {
    allowed = arma::ones<arma::mat>(4,4);
  } else {
    allowed = allowable_transitions;
  }
  
  if (allowed.n_rows != k || allowed.n_cols != k) {
    allowed = arma::ones(k, k);
  }
  
  Rcpp::RNGScope scope;
  if ((mode != "hmm") && (mode != "mm")) Rcpp::stop("Must have correct mode type.");
  
  int T1 = 0;
  int T = 0;
  if (mode == "hmm") {
    
    T = sequence.size();
    if (T == 0) Rcpp::stop("sequence must be non-empty.");
    if (k <= 0 || m <= 0) Rcpp::stop("k and m must be positive.");
    
    T1 = test_observations.size();
    if (T1 <= 0) Rcpp::stop("test sequence length must be positive when test_observations is empty.");
    
    for (int i = 0; i < sequence.length(); i++) {
      SEXP e = sequence[i];
      if (TYPEOF(e) == INTSXP) {
        if (Rcpp::as<Rcpp::IntegerVector>(e).length() != 2) {
          Rcpp::stop("Each value in sequence should be a tuple of integers of length 2.");
        }
      } else {
        Rcpp::stop("Each value in sequence should be a tuple of integers of length 2.");
      }
    }
    
  } else if (mode == "mm") {
    
    T = sequence.size();
    if (T == 0) Rcpp::stop("sequence must be non-empty.");
    if (k <= 0) Rcpp::stop("k must be positive.");
    
    if (pred_len <= 0) Rcpp::stop("pred_len must be positive when test_observations is empty.");
    T1 = pred_len;
    
    for (int i = 0; i < sequence.length(); i++) {
      SEXP e = sequence[i];
      if (TYPEOF(e) != INTSXP) {
        if (Rcpp::as<Rcpp::IntegerVector>(e).length() != 1) {
          Rcpp::stop("Each value in sequence should be a scalar integer");
        }
      }
    }
    
  }
  
  
  Rcpp::List cp_set;
  std::vector<int> state(T1, 0);
  bool done = false;
  // create a vector for each possible proposed state sequence you will store the eq_count.
  Rcpp::NumericVector eq_list;
  while (!done) {
    
    // Create the augmented sequence
    int aug_len = 0;
    int test_len = 0;
    if (add_zero) {
      aug_len = T+T1+1;
      test_len = T1+1;
    } else {
      aug_len = T+T1;
      test_len= T1;
    }
    Rcpp::List augmented(aug_len);
    
    if (mode == "hmm") {
      for (int i = 0; i < T; i++) augmented[i] = sequence[i];
      for (int i = 0; i < T1; i++) {
        int s = state[i];
        int o = test_observations[i];
        
        if (s < 0 || s >= k) Rcpp::stop("State out of range in candidate.");
        if (o < 0 || o >= m) Rcpp::stop("Observation out of range in test_observations.");
        
        augmented[T + i] = Rcpp::IntegerVector::create(s, o);
      }
      if (add_zero) {
        augmented[T + T1] = Rcpp::IntegerVector::create(0, 0);
      }
      
    } else if (mode == "mm") {
      for (int i = 0; i < T; i++) augmented[i] = Rcpp::IntegerVector::create(sequence[i], sequence[i]);
      for (int i = 0; i < pred_len; i++) {
        int s = state[i];
        int o = state[i];
        
        if (s < 0 || s >= k) Rcpp::stop("State out of range in candidate.");
        
        augmented[T + i] = Rcpp::IntegerVector::create(s, o);
      }
      if (add_zero) {
        augmented[T + T1] = Rcpp::IntegerVector::create(0, 0);
      }
      
    }
    
    bool allowed_sequence = true;
    for (int i = T - 1; i < augmented.size() - 1; i++) {
      int s1 = Rcpp::as<Rcpp::IntegerVector>(augmented[i])[0];
      int s2 = Rcpp::as<Rcpp::IntegerVector>(augmented[i+1])[0];
      if (allowed(s1, s2) == 0) {
        allowed_sequence = false;
        break;
      }
    }
    
    
    if (allowed_sequence) {
      arma::mat P_hat = estimate_transition_probabilities(augmented, k);
      arma::mat B_hat = arma::ones<arma::mat>(k, k);;
      if (mode == "hmm") {
        B_hat = estimate_observation_probabilities(augmented, k, m);
      } else if (mode == "mm") {
        B_hat = arma::ones<arma::mat>(k, k);
      }
      
      Rcpp::List blocks = ij_blocks(augmented);
      Rcpp::List permuted_lists = create_permutes(blocks, test_len, num_perms);
      
      int nb = static_cast<int>(blocks.size());
      int start_idx = std::max(0, nb - test_len - 1);
      Rcpp::List baseline_permute;
      
      for (int i = start_idx; i < nb; ++i) {
        Rcpp::List current_block = blocks[i];
        for (int j = 0; j < current_block.size(); ++j) {
          baseline_permute.push_back(Rcpp::as<Rcpp::IntegerVector>(current_block[j]));
        }
      }
      
      int M = permuted_lists.size();
      if (M <= 0) {
        
        cp_set.push_back(R_NilValue);
        
      } else {
        
        auto score_of = [&](Rcpp::List lst) -> double {
          double s = filter_subroutine_sum(P_hat, B_hat, test_len, lst);
          return 1.0 - (s / static_cast<double>(test_len));
        };
        
        double baseline = score_of(baseline_permute);
        int g_count = 0, eq_count = 0;
        double eps = 1e-12;
        
        for (int i = 0; i < M; i++) {
          Rcpp::List cand = Rcpp::as<Rcpp::List>(permuted_lists[i]);
          double sc = score_of(cand);
          if (sc >= baseline + eps) g_count += 1;
          if (std::abs(sc - baseline) <= eps) eq_count += 1;
        }
        double u = 0.0;
        if (coin_flip) {
          u = R::runif(0.0, 1.0);
        } else {
          u = 1.0;
        }
        double q = (static_cast<double>(g_count) + u * static_cast<double>(eq_count))
          / static_cast<double>(M);
        
        if (q > alpha) {
          Rcpp::IntegerVector keep(T1);
          for (int i = 0; i < T1; i++) keep[i] = state[i];
          cp_set.push_back(keep);
        }
        eq_list.push_back(eq_count);

      }
    }
    
    int pos = (T1) - 1;
    while (pos >= 0) {
      if (++state[pos] < k) break;
      state[pos] = 0;
      --pos;
    }
    if (pos < 0) done = true;
    
  }
  
  return Rcpp::List::create(
    Rcpp::Named("cp_set") = cp_set,
    Rcpp::Named("eq_list") = eq_list
  );
  
}


// [[Rcpp::export]]
double get_p_val(
    Rcpp::List& sequence,
    Rcpp::List& test_sequence,
    int num_perms, int k, int m,
    bool add_zero,
    std::string mode,
	bool coin_flip = true
) {
  
  Rcpp::RNGScope scope;
  
  // CHECKS
  if ((mode != "hmm") && (mode != "mm")) Rcpp::stop("Must have correct mode type.");
  
  int T = sequence.size();
  if (T == 0) Rcpp::stop("sequence must be non-empty.");
  if (mode == "hmm") {
    if (k <= 0 || m <= 0) Rcpp::stop("k and m must be positive.");
    
    for (int i = 0; i < sequence.length(); i++) {
      SEXP e = sequence[i];
      if (TYPEOF(e) == INTSXP) {
        if (Rcpp::as<Rcpp::IntegerVector>(e).length() != 2) {
          Rcpp::stop("Each value in sequence should be a tuple of integers of length 2.");
        }
      } else {
        Rcpp::stop("Each value in sequence should be a tuple of integers of length 2.");
      }
    }
    
    for (int i = 0; i < test_sequence.length(); i++) {
      SEXP e = test_sequence[i];
      if (TYPEOF(e) == INTSXP) {
        if (Rcpp::as<Rcpp::IntegerVector>(e).length() != 2) {
          Rcpp::stop("Each value in test_sequence should be a tuple of integers of length 2. (1)");
        }
      } else {
        Rcpp::stop("Each value in test_sequence should be a tuple of integers of length 2. (2)");
      }
    }
    
  } else if (mode == "mm") {
    if (k <= 0) Rcpp::stop("k must be positive.");
    
    for (int i = 0; i < sequence.length(); i++) {
      SEXP e = sequence[i];
      if (TYPEOF(e) != INTSXP) {
        if (Rcpp::as<Rcpp::IntegerVector>(e).length() != 1) {
          Rcpp::stop("Each value in sequence should be a scalar integer");
        }
      }
    }
    
    for (int i = 0; i < test_sequence.length(); i++) {
      SEXP e = test_sequence[i];
      if (TYPEOF(e) != INTSXP) {
        if (Rcpp::as<Rcpp::IntegerVector>(e).length() != 1) {
          Rcpp::stop("Each value in test_sequence should be a scalar integer");
        }
      }
    }
  }
  
  int T1 = test_sequence.size();
  if (T1 <= 0) Rcpp::stop("pred_len must be positive when test_observations is empty.");
  
  
  
  std::vector<int> state(T1, 0);
    
  // Create the augmented sequence
  int aug_len = 0;
  int test_len = 0;
  if (add_zero) {
    aug_len = T+T1+1;
    test_len = T1+1;
  } else {
    aug_len = T+T1;
    test_len= T1;
  }
  Rcpp::List augmented(aug_len);
  if (mode == "hmm") {
    
    for (int i = 0; i < T; i++) augmented[i] = sequence[i];
    for (int i = 0; i < T1; i++) augmented[T + i] = test_sequence[i];
    if (add_zero) {
      augmented[T + T1] = Rcpp::IntegerVector::create(0, 0);
    }
    
  } else if (mode == "mm") {
    
    for (int i = 0; i < T; i++) augmented[i] = Rcpp::IntegerVector::create(sequence[i], sequence[i]);
    for (int i = 0; i < T1; i++) augmented[T + i] = Rcpp::IntegerVector::create(test_sequence[i], test_sequence[i]);
    if (add_zero) {
      augmented[T + T1] = Rcpp::IntegerVector::create(0, 0);
    }
    
  }
  
  
  arma::mat P_hat = estimate_transition_probabilities(augmented, k);
  arma::mat B_hat;
  if (mode == "hmm") {
    B_hat = estimate_observation_probabilities(augmented, k, m);
  } else if (mode == "mm") {
    B_hat = arma::ones<arma::mat>(k, k);
  }
  Rcpp::List blocks = ij_blocks(augmented);
  Rcpp::List permuted_lists = create_permutes(blocks, test_len, num_perms);
  
  int nb = static_cast<int>(blocks.size());
  int start_idx = std::max(0, nb - test_len - 1);
  Rcpp::List baseline_permute;
  
  for (int i = start_idx; i < nb; ++i) {
    Rcpp::List current_block = blocks[i];
    for (int j = 0; j < current_block.size(); ++j) {
      baseline_permute.push_back(Rcpp::as<Rcpp::IntegerVector>(current_block[j]));
    }
  }
  
  int M = permuted_lists.size();
  if (M <= 0) {
    
    return 0;
    
  } else {
    
    auto score_of = [&](Rcpp::List lst) -> double {
      double s = filter_subroutine_sum(P_hat, B_hat, test_len, lst);
      return 1.0 - (s / static_cast<double>(test_len));
    };
    
    double baseline = score_of(baseline_permute);
    int g_count = 0, eq_count = 0;
    double eps = 1e-12;
    
    for (int i = 0; i < M; i++) {
      Rcpp::List cand = Rcpp::as<Rcpp::List>(permuted_lists[i]);
      double sc = score_of(cand);
      if (sc >= baseline + eps) g_count += 1;
      if (std::abs(sc - baseline) <= eps) eq_count += 1;
    }
	double u = 0.0;
    if (coin_flip) {
		u = R::runif(0.0, 1.0);
	} else {
		u = 1.0;
	}
    double q = (static_cast<double>(g_count) + u * static_cast<double>(eq_count))
      / static_cast<double>(M);
  
    return q;
    
  }
}
